INSERT INTO DEPARTMENTS (ID, NAME) VALUES (1, 'Human Resources');
INSERT INTO DEPARTMENTS (ID, NAME) VALUES (2, 'Finance');
INSERT INTO DEPARTMENTS (ID, NAME) VALUES (3, 'IT');

INSERT INTO USERS (ID, NAME, DEPARTMENT_ID) VALUES (1, 'Alice', 1);
INSERT INTO USERS (ID, NAME, DEPARTMENT_ID) VALUES (2, 'Bob', 1);
INSERT INTO USERS (ID, NAME, DEPARTMENT_ID) VALUES (3, 'Charlie', 1);
INSERT INTO USERS (ID, NAME, DEPARTMENT_ID) VALUES (4, 'David', 2);
INSERT INTO USERS (ID, NAME, DEPARTMENT_ID) VALUES (5, 'Eve', 2);
INSERT INTO USERS (ID, NAME, DEPARTMENT_ID) VALUES (6, 'Frank', 2);
INSERT INTO USERS (ID, NAME, DEPARTMENT_ID) VALUES (7, 'Grace', 3);
INSERT INTO USERS (ID, NAME, DEPARTMENT_ID) VALUES (8, 'Heidi', 3);
INSERT INTO USERS (ID, NAME, DEPARTMENT_ID) VALUES (9, 'Ivan', 3);